import "./globals.css";
import localFont from "next/font/local";
import { ViewTransitions } from "next-view-transitions";

const tommyRegular = localFont({
  variable: "--font-tommy-regular",
  src: [
    {
      path: "./fonts/MADETOMMY_Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
});

const tommyLight = localFont({
  variable: "--font-tommy-light",
  src: [
    {
      path: "./fonts/MADETOMMY_Light.otf",
      weight: "300",
      style: "normal",
    },
  ],
});

const tommyBlack = localFont({
  variable: "--font-tommy-black",
  src: [
    {
      path: "./fonts/MADETOMMY_Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
});

const tommyBold = localFont({
  variable: "--font-tommy-bold",
  src: [
    {
      path: "./fonts/MADETOMMY_Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

const tommyExtraBold = localFont({
  variable: "--font-tommy-extraBold",
  src: [
    {
      path: "./fonts/MADETOMMY_ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
});
const tommyMedium = localFont({
  variable: "--font-tommy-medium",
  src: [
    {
      path: "./fonts/MADETOMMY_Medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "UX GFX®",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${tommyBlack.variable} ${tommyRegular.variable} ${tommyLight.variable} ${tommyBold.variable} ${tommyExtraBold.variable} ${tommyMedium.variable} antialiased bg-[#121212]`}
        >
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
